### ISSUE TITLE
Can't process URL

### ISSUE THREAD

**Issue by jimwebb** [factcheckthenews/website#1]
This URL doesn't seem to work (it's a hilarious fake news site): 

http://thelastlineofdefense.org/breaking-isis-walks-right-past-security-at-jfk-how-liberals-greeted-them-is-sick/

Great project!

**Comment by uncompiled** [comment]
Right now, it gets a 78% because there aren't enough red flags.  opensources.co relies on people reporting websites and a team of people to vet submissions, so I'm thinking about making the Web of Trust reputation a larger weight of the overall score.
